apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: azure-iot-operations
  labels:
    app: contosowebapp
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: contosowebapp
  template:
    metadata:
      labels:
        app: contosowebapp
    spec:
      containers:
      - name: contosowebapp
        image: agoraarmbladev.azurecr.io/contosowebapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: azure-iot-operations
spec:
  selector:
    app: contosowebapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

