apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-simulator-deployment
  namespace: azure-iot-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-simulator
  template:
    metadata:
      labels:
        app: mqtt-simulator
    spec:
      containers:
        - name: mqtt-simulator
          image: agoraarmbladev.azurecr.io/mqtt-simulator:latest
          env:
            - name: MQTT_BROKER
              value: {{ .Values.mqBrokerEndpoint }} 
            - name: MQTT_PORT
              value: {{ .Values.mqBrokerEndpointPort | quote }}
            - name: FRECUENCY
              value: "10"
